# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - lms2-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish LMS.API -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: dotnet publish web
        run: dotnet publish LMS.Blazor/LMS.Blazor -c Release -o "${{env.DOTNET_ROOT}}/myweb"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Upload web artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-web
          path: ${{env.DOTNET_ROOT}}/myweb

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9B8D2239CEEA435EB4DE74A6FC0713F6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E81D81A214ED4A09A8124D3A42A05535 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E0C11F8454134318A98E8A9E8B251FD0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "lms2-api"
          slot-name: "Production"
          package: api

      - name: Download web artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-web
          path: web

      - name: Deploy web to Azure Web App
        id: deploy-web-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "lms2-web"
          slot-name: "Production"
          package: web
